### PR TITLE
Update myself to be a contributor

### PR DESCRIPTION
**Pull request by Popaulol**

### CODE REVIEW

**Review by linusg — COMMENTED** [review]
https://github.com/SerenityOS/serenity/commits?author=Popaulol

> No commits found for "Popaulol"

**Comment by Popaulol** [comment]
What? Wait I'll give a link to the 2 prs I did in a few secs...

**Comment by Popaulol** [comment]
https://github.com/SerenityOS/serenity/pull/16906
https://github.com/SerenityOS/serenity/pull/16870

**Comment by Popaulol** [comment]
My best guess is that thjs is probably a result of the fact that the git on my PC system is using a different email and Username than my GitHub account. So the actual commits Aren't authored by this account...

**Comment by linusg** [comment]
aha - consider adding `staubfingercodinggames@gmail.com` to your GitHub account (https://github.com/settings/emails) so the commits are properly attributed to you :)

**Comment by Popaulol** [comment]
Yes, I've checked in the commits and GitHub attributes the commits to an an account by a different person, that happens to use my main only Nickname "Staubfinger" as their GH name...

**Comment by Popaulol** [comment]
> aha - consider adding `staubfingercodinggames@gmail.com` to your GitHub account (https://github.com/settings/emails) so the commits are properly attributed to you :)

Yeah, I've now added it and now it correctly detects the commits as being mine. Thank you.

**Pull request merged**
